import { PhotoMetaData } from "./definitions";

export const pictures: PhotoMetaData[] = [
  {
    src: "/photos/antips_1.jpg",
    id: "antips_1",
    title: "Antipolo Ride",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/antips_2.jpg",
    id: "antips_2",
    title: "Antipolo Ride",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/antips_3.jpg",
    id: "antips_3",
    title: "Antipolo Ride",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/antips_4.jpg",
    id: "antips_4",
    title: "Antipolo Ride",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/antips_5.jpg",
    id: "antips_5",
    title: "Antipolo Ride",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/antips_6.jpg",
    id: "antips_6",
    title: "Antipolo Ride",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/drifting_1.jpg",
    id: "drifting_1",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/drifting_2.jpg",
    id: "drifting_2",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/drifting_3.jpg",
    id: "drifting_3",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/drifting_4.jpg",
    id: "drifting_4",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/edsa_1.jpg",
    id: "edsa",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/engineered_1.jpg",
    id: "engineered_1",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/engineered_2.jpg",
    id: "engineered_2",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/engineered_3.jpg",
    id: "engineered_3",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/engineered_4.jpg",
    id: "engineered_4",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/flower_1.jpg",
    id: "flower_1",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/moa_1.jpg",
    id: "moa_1",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/moa_2.jpg",
    id: "moa_2",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/promenade_3.jpg",
    id: "promenade_3",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/promenade_1.jpg",
    id: "promenade_1",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/promenade_2.jpg",
    id: "promenade_2",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
  {
    src: "/photos/worm_1.png",
    id: "worm_1",
    title: "Tambay Drift",
    desc: "got late to tree planting for this one",
    date: "Sept 12, 2026",
    category: "Vehicles",
    camera: "Olympus OM-D E-M5",
    lens: "Kit",
  },
];
